run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - gofmt
    - errcheck
    - staticcheck
    - gocyclo
    - gosimple

linters-settings:
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
