name: CI

on:
  push:
    branches: [ develop, main, master ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Print Go version
        run: go version

      - name: Install ripgrep (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep

      - name: Install ripgrep (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ripgrep

      - name: Install make and ripgrep (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          choco install -y make ripgrep
          echo "make version:"; make --version || true
          echo "rg version:"; rg --version || true

      - name: Print Go env
        run: go env

      - name: Tidy
        shell: bash
        run: make tidy

      - name: lint (includes check-go-version)
        shell: bash
        run: make lint

      - name: Tools path hygiene
        shell: bash
        run: make check-tools-paths

      - name: Verify tools manifest commands
        shell: bash
        run: make verify-manifest-paths

      - name: Test
        shell: bash
        run: make test

      - name: Test clean-logs guard
        shell: bash
        run: make test-clean-logs

      - name: Build
        shell: bash
        run: make build

      - name: Build tools
        shell: bash
        run: make build-tools
